"""
Educational Compliance Module for Student Advisor Platform

Provides utilities to ensure AI responses are educational and informative.
Includes multilingual disclaimers and system prompts.

Author: Student Advisor Team
Date: 2025-12-19
"""

from typing import Dict, Optional
import re


class UPLCompliance:
    """
    Centralized educational compliance utilities for Student Advisor AI assistant.
    
    Ensures all AI responses:
    - Include proper disclaimers
    - Provide legal information (not advice)
    - Follow safe zone guidelines
    - Comply with regulations across all 10 jurisdictions
    """
    
    # Multilingual disclaimers for all 10 supported languages
    DISCLAIMERS = {
        'sk': "⚠️ Student Advisor je vzdelávacia platforma a neposkytuje profesionálne poradenstvo. Táto informácia je určená len na všeobecné vzdelávacie účely.",
        
        'en': "⚠️ Student Advisor is an educational platform and does not provide professional advice. This information is intended for general educational purposes only.",
        
        'uk': "⚠️ Student Advisor є освітньою платформою і не надає професійних консультацій. Ця інформація призначена лише для загальних освітніх цілей.",
        
        'ru': "⚠️ Student Advisor является образовательной платформой и не предоставляет профессиональных консультаций. Эта информация предназначена только для общих образовательных целей.",
        
        'de': "⚠️ Student Advisor ist eine Bildungsplattform und bietet keine professionelle Beratung an. Diese Informationen dienen nur allgemeinen Bildungszwecken.",
        
        'it': "⚠️ Student Advisor è una piattaforma educativa e non fornisce consulenza professionale. Queste informazioni sono destinate solo a scopi educativi generali.",
        
        'fr': "⚠️ Student Advisor est une plateforme éducative et ne fournit pas de conseils professionnels. Ces informations sont destinées uniquement à des fins éducatives générales.",
        
        'es': "⚠️ Student Advisor es una plataforma educativa y no proporciona asesoramiento profesional. Esta información está destinada solo para fines educativos generales.",
        
        'pl': "⚠️ Student Advisor jest platformą edukacyjną i nie świadczy profesjonalnych usług doradczych. Te informacje są przeznaczone wyłącznie do ogólnych celów edukacyjnych.",
        
        'cs': "⚠️ Student Advisor je vzdělávací platforma a neposkytuje profesionální poradenství. Tyto informace jsou určeny pouze pro všeobecné vzdělávací účely."
    }
    
    # Document generation disclaimer
    DOCUMENT_DISCLAIMERS = {
        'sk': """
⚠️ ZASTEREЖЕННЯ:
Tento dokument bol vygenerovaný AI a nebol preverený právnikom.
Použite ho ako šablónu. Odporúčame overenie licencovaným advokátom pred použitím.
""",
        'en': """
⚠️ DISCLAIMER:
This document was generated by AI and has not been reviewed by a lawyer.
Use it as a template. We recommend verification by a licensed attorney before use.
""",
        'uk': """
⚠️ ЗАСТЕРЕЖЕННЯ:
Цей документ згенеровано AI і не переглянутий юристом.
Використовуйте його як шаблон. Рекомендуємо перевірку ліцензованим адвокатом перед використанням.
""",
        'ru': """
⚠️ ПРЕДУПРЕЖДЕНИЕ:
Этот документ был сгенерирован AI и не проверен юристом.
Используйте его как шаблон. Рекомендуем проверку лицензированным адвокатом перед использованием.
""",
        'de': """
⚠️ HAFTUNGSAUSSCHLUSS:
Dieses Dokument wurde von AI generiert und nicht von einem Anwalt überprüft.
Verwenden Sie es als Vorlage. Wir empfehlen eine Überprüfung durch einen zugelassenen Rechtsanwalt vor der Verwendung.
""",
        'it': """
⚠️ DISCLAIMER:
Questo documento è stato generato da AI e non è stato revisionato da un avvocato.
Usalo come modello. Raccomandiamo la verifica da parte di un avvocato autorizzato prima dell'uso.
""",
        'fr': """
⚠️ AVERTISSEMENT:
Ce document a été généré par AI et n'a pas été vérifié par un avocat.
Utilisez-le comme modèle. Nous recommandons une vérification par un avocat agréé avant utilisation.
""",
        'es': """
⚠️ DESCARGO DE RESPONSABILIDAD:
Este documento fue generado por AI y no ha sido revisado por un abogado.
Úselo como plantilla. Recomendamos verificación por un abogado licenciado antes de usar.
""",
        'pl': """
⚠️ ZASTRZEŻENIE:
Ten dokument został wygenerowany przez AI i nie został sprawdzony przez prawnika.
Użyj go jako szablonu. Zalecamy weryfikację przez licencjonowanego adwokata przed użyciem.
""",
        'cs': """
⚠️ UPOZORNĚNÍ:
Tento dokument byl vygenerován AI a nebyl zkontrolován právníkem.
Použijte jej jako šablonu. Doporučujeme ověření licencovaným advokátem před použitím.
"""
    }
    
    @staticmethod
    def get_disclaimer(language: str = 'sk') -> str:
        """
        Get UPL disclaimer in specified language.
        
        Args:
            language: Language code (sk, en, uk, ru, de, it, fr, es, pl, cs)
            
        Returns:
            Disclaimer text in specified language
        """
        return UPLCompliance.DISCLAIMERS.get(language, UPLCompliance.DISCLAIMERS['sk'])
    
    @staticmethod
    def get_document_disclaimer(language: str = 'sk') -> str:
        """
        Get document generation disclaimer in specified language.
        
        Args:
            language: Language code
            
        Returns:
            Document disclaimer text
        """
        return UPLCompliance.DOCUMENT_DISCLAIMERS.get(language, UPLCompliance.DOCUMENT_DISCLAIMERS['sk'])
    
    @staticmethod
    def get_system_prompt(language: str = 'sk') -> str:
        """
        Get UPL-compliant system prompt for AI assistant.
        
        Args:
            language: Language code for response language
            
        Returns:
            UPL-compliant system prompt
        """
        # Multilingual system prompts
        prompts = {
            'sk': """Si asistent pre právne informácie (NIE právnik) špecializujúci sa na slovenské právo.

🔵 ČO MÔŽEŠ ROBIŤ (Safe Zone):
✅ Vysvetľovať všeobecné právne princípy
   Príklad: "Na Slovensku Občiansky zákonník upravuje zmluvy v §§ 34-51..."
   
✅ Ukazovať relevantné články zákonov
   Príklad: "Podľa § 97 Zákonníka práce, práca cez víkend sa kompenzuje..."
   
✅ Poskytovať šablóny dokumentov s disclaimerom
   Príklad: "Tu je vzorová sťažnosť. ⚠️ Odporúčam overenie právnikom."
   
✅ Vysvetľovať právne procedúry
   Príklad: "Proces podania sťažnosti: 1) Napísať sťažnosť, 2) Podať na súd..."
   
✅ Analyzovať dokumenty s disclaimerom
   Príklad: "V tejto zmluve vidím tieto riziká... ⚠️ Toto je všeobecná analýza, nie právna rada."

❌ ČO NESMIEŠ ROBIŤ (Red Zone):
❌ Konkrétne právne rady pre prípad používateľa
   ZLYHANIE: "VY by ste mali podať žalobu"
   SPRÁVNE: "Všeobecne, pri porušení zmluvy možno podať žalobu. Odporúčam konzultáciu s advokátom."

❌ Interpretácia zákona pre konkrétnu situáciu
   ZLYHANIE: "Tento zákon znamená, že VY máte nárok na €500"
   SPRÁVNE: "Podľa tohto zákona môže vzniknúť nárok na kompenzáciu. Pre posúdenie VÁŠHO prípadu kontaktujte advokáta."

❌ Garancie výsledkov
   ZLYHANIE: "Určite vyhráte súd"
   SPRÁVNE: "Výsledok závisí od mnohých faktorov. Advokát posúdi vaše šance."

❌ Zastupovanie
   ZLYHANIE: "Napíšem pozov za vás"
   SPRÁVNE: "Môžem ukázať vzor pozvu. Odporúčam, aby ho pripravil advokát."

⚠️ POVINNÉ PRAVIDLÁ:
1. VŽDY začni odpoveď disclaimerom: "🤖 Student Advisor je vzdelávacia platforma..."
2. NIKDY nepoužívaj "VY by ste mali", "VÁŠ prípad", "určite vyhráte"
3. VŽDY odporúčaj konzultáciu s advokátom pre konkrétne situácie
4. Používaj "všeobecne", "zvyčajne", "môže", nie "musíte", "určite"

Odpovedaj v slovenčine, jasne a profesionálne.""",

            'en': """You are a legal information assistant (NOT a lawyer) specializing in law.

🔵 WHAT YOU CAN DO (Safe Zone):
✅ Explain general legal principles
✅ Show relevant law articles
✅ Provide document templates with disclaimers
✅ Explain legal procedures
✅ Analyze documents with "general analysis" disclaimer

❌ WHAT YOU CANNOT DO (Red Zone):
❌ Specific legal advice for user's case
❌ Interpret law for specific situation
❌ Guarantee case outcomes
❌ Represent users
❌ Use phrases like "you MUST", "you WILL WIN"

⚠️ MANDATORY RULES:
1. ALWAYS start response with: "🤖 Student Advisor is an educational platform..."
2. NEVER use "YOU should", "YOUR case will", "definitely win"
3. ALWAYS recommend consulting licensed attorney for specific situations
4. Use "generally", "typically", "may", not "must", "definitely"

Respond in English, clearly and professionally."""
        }
        
        # Default to Slovak if language not found
        return prompts.get(language, prompts['sk'])
    
    @staticmethod
    def inject_disclaimer(response: str, language: str = 'sk') -> str:
        """
        Inject disclaimer at the beginning of AI response.
        
        Args:
            response: Original AI response
            language: Language code
            
        Returns:
            Response with disclaimer prepended
        """
        disclaimer = UPLCompliance.get_disclaimer(language)
        
        # Check if disclaimer already exists
        if disclaimer in response or "⚠️ Student Advisor" in response[:200]:
            return response
        
        return f"{disclaimer}\n\n{response}"
    
    @staticmethod
    def validate_response_compliance(response: str, language: str = 'sk') -> Dict[str, any]:
        """
        Validate if AI response complies with UPL regulations.
        
        Args:
            response: AI response to validate
            language: Language code
            
        Returns:
            Dictionary with validation results:
            - is_compliant: bool
            - violations: list of detected violations
            - warnings: list of potential issues
        """
        violations = []
        warnings = []
        
        # Check for forbidden phrases (Slovak)
        if language == 'sk':
            forbidden_patterns = [
                (r'\bvy by ste mali\b', "Uses 'vy by ste mali' (you should)"),
                (r'\bvýš prípad\b', "Uses 'váš prípad' (your case)"),
                (r'\burčite vyhráte\b', "Guarantees outcome 'určite vyhráte'"),
                (r'\bnapíšem (pozov|žalobu) za vás\b', "Offers to write legal documents"),
                (r'\bmáte nárok na\b', "States specific entitlement 'máte nárok na'"),
            ]
            
            for pattern, violation in forbidden_patterns:
                if re.search(pattern, response, re.IGNORECASE):
                    violations.append(violation)
        
        # Check for disclaimer presence
        if "⚠️" not in response[:300] and "Student Advisor" not in response[:300]:
            warnings.append("Disclaimer may be missing or not at the beginning")
        
        # Check for recommendation to consult lawyer
        lawyer_keywords = {
            'sk': ['advokát', 'právnik', 'konzultácia'],
            'en': ['attorney', 'lawyer', 'consult'],
            'uk': ['адвокат', 'юрист', 'консультація'],
            'ru': ['адвокат', 'юрист', 'консультация'],
        }
        
        keywords = lawyer_keywords.get(language, lawyer_keywords['sk'])
        has_lawyer_recommendation = any(keyword in response.lower() for keyword in keywords)
        
        if not has_lawyer_recommendation and len(response) > 200:
            warnings.append("No recommendation to consult a lawyer")
        
        return {
            'is_compliant': len(violations) == 0,
            'violations': violations,
            'warnings': warnings
        }
    
    @staticmethod
    def detect_language(text: str) -> str:
        """
        Detect language from text (simple heuristic).
        
        Args:
            text: Text to analyze
            
        Returns:
            Detected language code
        """
        # Simple keyword-based detection
        language_indicators = {
            'sk': ['slovensko', 'zákon', 'právny', 'zmluva', 'súd'],
            'en': ['law', 'legal', 'contract', 'court', 'attorney'],
            'uk': ['україна', 'закон', 'юридичний', 'договір', 'суд'],
            'ru': ['россия', 'закон', 'юридический', 'договор', 'суд'],
            'de': ['deutschland', 'gesetz', 'rechtlich', 'vertrag', 'gericht'],
            'pl': ['polska', 'prawo', 'prawny', 'umowa', 'sąd'],
            'cs': ['česko', 'zákon', 'právní', 'smlouva', 'soud'],
        }
        
        text_lower = text.lower()
        
        for lang, keywords in language_indicators.items():
            if any(keyword in text_lower for keyword in keywords):
                return lang
        
        # Default to Slovak
        return 'sk'


# Convenience functions for easy import
def get_disclaimer(language: str = 'sk') -> str:
    """Get UPL disclaimer in specified language."""
    return UPLCompliance.get_disclaimer(language)


def get_system_prompt(language: str = 'sk') -> str:
    """Get UPL-compliant system prompt."""
    return UPLCompliance.get_system_prompt(language)


def inject_disclaimer(response: str, language: str = 'sk') -> str:
    """Inject disclaimer into AI response."""
    return UPLCompliance.inject_disclaimer(response, language)


def validate_compliance(response: str, language: str = 'sk') -> Dict:
    """Validate AI response compliance."""
    return UPLCompliance.validate_response_compliance(response, language)
